### ISSUE TITLE
Support for 'is typing...'

### ISSUE THREAD

**Issue by Stevenje** [detritusjs/client-socket#5]
Hey,

First of all great work, I've been really enjoying this library. Thank you!! 

Would it be possible to add support for 'is typing...' so that I can listen for that event. 

EG when a member is typing it shows up on the bottom of the client. 

Thanks a lot.

**Comment by Stevenje** [comment]
Just realised there is a 'TYPING_START' support but only for private messages (DMs)

Would it be possible to add it for group chats / channels as well.

**Comment by cakedan** [comment]
'TYPING_START' is supported for all channels, theres no special case for just DMs.

https://discord.com/developers/docs/topics/gateway#typing-start

**Comment by Stevenje** [comment]
I'm listening for 'TYPING_START' but I'm only getting packets on private messages / DM's 

```ts
if (packet.t === 'TYPING_START') {
      try {
        logger.info(packet.d.user_id + ' is typing.. - ' + packet.d.channel_id);
        logger.debug('TYPING_START: ' + packet.d);
      } catch (error) {
        console.error('[TYPING]' + error.message);
      }
    } 
```

Is there something I need to do to configure to get these alerts? Otherwise I think there might be a bug.

**Comment by Tehi** [comment]
Do you have right intents? There is one for guild message typing and one for direct message typing.
https://discord.com/developers/docs/topics/gateway#list-of-intents

**Comment by Stevenje** [comment]
Just set the  'GUILD_MESSAGE_TYPING' intent. Although still no luck. :/

```ts
  const client = new Gateway.Socket(token, {
    intents: ['GUILD_MESSAGES', 'GUILD_MESSAGE_TYPING'],
  });

  client.on('ready', () => {
    logger.info('Discord Client Operational');
  });

  client.on('packet', (packet) => handleDiscordPacket(packet));

  client.on('close', (event) => logger.warn('client close', event));
  client.on('warn', logger.error);

  client.connect('wss://gateway.discord.gg/');
```

**Comment by cakedan** [comment]
Are you using a bot token? User tokens aren't really supporter since they're against the TOS. For the sake of knowledge though, they have a different way of getting events. Bots freely get events based off intents. Other than that I'm not sure why you wouldn't be getting typing events for guilds.
