### ISSUE TITLE
Packet Content Empty

### ISSUE THREAD

**Issue by Stevenje** [detritusjs/client-socket#6]
Since about 3 hours ago the content field for packets has been comming through as `content: '',` on all packets. I'm still getting other fields including quoted content. But the main message content is missing on all packets.

Initally I thought it could be a dependacy update as it started after a new build was deployed on my server, although ive reverted to prior builds and it hasn't resolved it.

Would really appreciate any advice as to how I could remedy this. Thanks a lot.

<img width="220" alt="image" src="https://user-images.githubusercontent.com/4363358/116707361-338c0380-a994-11eb-8bbe-3fe2a0591815.png">

``` ts
this.packet
 {
  t: 'MESSAGE_CREATE',
  s: 13,
  op: 0,
  d: {
    webhook_id: '1234',
    type: 0,
    tts: false,
    timestamp: '2021 pinned: false,
    mentions: [],
    mention_roles: [],
    mention_everyone: false,
    id: '1234',
    flags: 0,
    embeds: [],
    edited_timestamp: null,
    content: '',    <---
    components: [],
    channel_id: '1233',
    author: {
    username: 'GitHub',
    id: '000000',
    discriminator: '0000',
    bot: true,
    avatar: 'kjsdhflkjsdhalfh'
  },
  attachments: [],
  guild_id: '12334'
  }
 }
```

**Comment by Ssaely** [comment]
This is from Discord acting against selfbots.

**Comment by Stevenje** [comment]
> This is from Discord acting against selfbots.

Are you aware of any libraries that are able to get around this? I'm only looking to get access to message content.

**Comment by Pechu317** [comment]
> > This is from Discord acting against selfbots.
> 
> Are you aware of any libraries that are able to get around this? I'm only looking to get access to message content.

using selfbots is against discord TOS. no matter what, the only allowed way to interact with a user account is to use the official discord client.

**Comment by dawnofmidnight** [comment]
> > > This is from Discord acting against selfbots.
> > 
> > 
> > Are you aware of any libraries that are able to get around this? I'm only looking to get access to message content.
> 
> using selfbots is against discord TOS. no matter what, the only allowed way to interact with a user account is to use the official discord client.

They're not trying to selfbot, they're trying to get around the problems Discord is causing by adding these new measures,

**Comment by justsomederpystuff** [comment]
> > > > This is from Discord acting against selfbots.
> > > 
> > > 
> > > Are you aware of any libraries that are able to get around this? I'm only looking to get access to message content.
> > 
> > using selfbots is against discord TOS. no matter what, the only allowed way to interact with a user account is to use the official discord client.
> 
> They're not trying to selfbot, they're trying to get around the problems Discord is causing by adding these new measures,
> 

The new measures only apply to regular user accounts. Bots are unaffected.

**Comment by iamlongpant** [comment]
> 
> 
> > This is from Discord acting against selfbots.
> 
> Are you aware of any libraries that are able to get around this? I'm only looking to get access to message content.

The reason why you aren't receiving message contents is because Discord has detected that you are not using the official client. You should ***NEVER*** use the gateway API with a client other than the official client, it is extremely easy for Discord to detect that you are not using the official client.

But to answer your question, you can use the IPC API to receive message events with this module: https://www.npmjs.com/package/rpcord

**Comment by Stevenje** [comment]
> > > This is from Discord acting against selfbots.
> > 
> > 
> > Are you aware of any libraries that are able to get around this? I'm only looking to get access to message content.
> 
> The reason why you aren't receiving message contents is because Discord has detected that you are not using the official client. You should _**NEVER**_ use the gateway API with a client other than the official client, it is trivial for Discord to detect that you are not using the official client.
> 
> But to answer your question, you can use the IPC API (which as far as I know, does not violate TOS) to receive message events with this module: https://www.npmjs.com/package/rpcord

Hey, Thanks for the response. I tried your above solution using the IPC API but couldnt get it to function. I'm joining a channel and listening for messages with certain keywords and forwarding myself slack notifications. I dont really use Discord for much else, so if I did get banned its not too big of an issue. Do you know of any other soltions that currently function?
